// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/zmb3/spotify/v2"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddTracksToPlaylist provides a mock function for the type MockClient
func (_mock *MockClient) AddTracksToPlaylist(ctx context.Context, playlistID spotify.ID, trackIDs ...spotify.ID) (string, error) {
	var tmpRet mock.Arguments
	if len(trackIDs) > 0 {
		tmpRet = _mock.Called(ctx, playlistID, trackIDs)
	} else {
		tmpRet = _mock.Called(ctx, playlistID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddTracksToPlaylist")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spotify.ID, ...spotify.ID) (string, error)); ok {
		return returnFunc(ctx, playlistID, trackIDs...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spotify.ID, ...spotify.ID) string); ok {
		r0 = returnFunc(ctx, playlistID, trackIDs...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spotify.ID, ...spotify.ID) error); ok {
		r1 = returnFunc(ctx, playlistID, trackIDs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_AddTracksToPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTracksToPlaylist'
type MockClient_AddTracksToPlaylist_Call struct {
	*mock.Call
}

// AddTracksToPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID spotify.ID
//   - trackIDs ...spotify.ID
func (_e *MockClient_Expecter) AddTracksToPlaylist(ctx interface{}, playlistID interface{}, trackIDs ...interface{}) *MockClient_AddTracksToPlaylist_Call {
	return &MockClient_AddTracksToPlaylist_Call{Call: _e.mock.On("AddTracksToPlaylist",
		append([]interface{}{ctx, playlistID}, trackIDs...)...)}
}

func (_c *MockClient_AddTracksToPlaylist_Call) Run(run func(ctx context.Context, playlistID spotify.ID, trackIDs ...spotify.ID)) *MockClient_AddTracksToPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spotify.ID
		if args[1] != nil {
			arg1 = args[1].(spotify.ID)
		}
		var arg2 []spotify.ID
		var variadicArgs []spotify.ID
		if len(args) > 2 {
			variadicArgs = args[2].([]spotify.ID)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_AddTracksToPlaylist_Call) Return(snapshotID string, err error) *MockClient_AddTracksToPlaylist_Call {
	_c.Call.Return(snapshotID, err)
	return _c
}

func (_c *MockClient_AddTracksToPlaylist_Call) RunAndReturn(run func(ctx context.Context, playlistID spotify.ID, trackIDs ...spotify.ID) (string, error)) *MockClient_AddTracksToPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlaylistItems provides a mock function for the type MockClient
func (_mock *MockClient) GetPlaylistItems(ctx context.Context, playlistID spotify.ID, opts ...spotify.RequestOption) (*spotify.PlaylistItemPage, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, playlistID, opts)
	} else {
		tmpRet = _mock.Called(ctx, playlistID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPlaylistItems")
	}

	var r0 *spotify.PlaylistItemPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spotify.ID, ...spotify.RequestOption) (*spotify.PlaylistItemPage, error)); ok {
		return returnFunc(ctx, playlistID, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spotify.ID, ...spotify.RequestOption) *spotify.PlaylistItemPage); ok {
		r0 = returnFunc(ctx, playlistID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spotify.PlaylistItemPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spotify.ID, ...spotify.RequestOption) error); ok {
		r1 = returnFunc(ctx, playlistID, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetPlaylistItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlaylistItems'
type MockClient_GetPlaylistItems_Call struct {
	*mock.Call
}

// GetPlaylistItems is a helper method to define mock.On call
//   - ctx context.Context
//   - playlistID spotify.ID
//   - opts ...spotify.RequestOption
func (_e *MockClient_Expecter) GetPlaylistItems(ctx interface{}, playlistID interface{}, opts ...interface{}) *MockClient_GetPlaylistItems_Call {
	return &MockClient_GetPlaylistItems_Call{Call: _e.mock.On("GetPlaylistItems",
		append([]interface{}{ctx, playlistID}, opts...)...)}
}

func (_c *MockClient_GetPlaylistItems_Call) Run(run func(ctx context.Context, playlistID spotify.ID, opts ...spotify.RequestOption)) *MockClient_GetPlaylistItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spotify.ID
		if args[1] != nil {
			arg1 = args[1].(spotify.ID)
		}
		var arg2 []spotify.RequestOption
		var variadicArgs []spotify.RequestOption
		if len(args) > 2 {
			variadicArgs = args[2].([]spotify.RequestOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockClient_GetPlaylistItems_Call) Return(playlistItemPage *spotify.PlaylistItemPage, err error) *MockClient_GetPlaylistItems_Call {
	_c.Call.Return(playlistItemPage, err)
	return _c
}

func (_c *MockClient_GetPlaylistItems_Call) RunAndReturn(run func(ctx context.Context, playlistID spotify.ID, opts ...spotify.RequestOption) (*spotify.PlaylistItemPage, error)) *MockClient_GetPlaylistItems_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockClient
func (_mock *MockClient) Search(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption) (*spotify.SearchResult, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, query, t, opts)
	} else {
		tmpRet = _mock.Called(ctx, query, t)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *spotify.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, spotify.SearchType, ...spotify.RequestOption) (*spotify.SearchResult, error)); ok {
		return returnFunc(ctx, query, t, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, spotify.SearchType, ...spotify.RequestOption) *spotify.SearchResult); ok {
		r0 = returnFunc(ctx, query, t, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spotify.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, spotify.SearchType, ...spotify.RequestOption) error); ok {
		r1 = returnFunc(ctx, query, t, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockClient_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - t spotify.SearchType
//   - opts ...spotify.RequestOption
func (_e *MockClient_Expecter) Search(ctx interface{}, query interface{}, t interface{}, opts ...interface{}) *MockClient_Search_Call {
	return &MockClient_Search_Call{Call: _e.mock.On("Search",
		append([]interface{}{ctx, query, t}, opts...)...)}
}

func (_c *MockClient_Search_Call) Run(run func(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption)) *MockClient_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 spotify.SearchType
		if args[2] != nil {
			arg2 = args[2].(spotify.SearchType)
		}
		var arg3 []spotify.RequestOption
		var variadicArgs []spotify.RequestOption
		if len(args) > 3 {
			variadicArgs = args[3].([]spotify.RequestOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockClient_Search_Call) Return(searchResult *spotify.SearchResult, err error) *MockClient_Search_Call {
	_c.Call.Return(searchResult, err)
	return _c
}

func (_c *MockClient_Search_Call) RunAndReturn(run func(ctx context.Context, query string, t spotify.SearchType, opts ...spotify.RequestOption) (*spotify.SearchResult, error)) *MockClient_Search_Call {
	_c.Call.Return(run)
	return _c
}
