// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"joeradio/provider"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// AddToPlaylist provides a mock function for the type MockProvider
func (_mock *MockProvider) AddToPlaylist(ctx context.Context, trackID string) error {
	ret := _mock.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for AddToPlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_AddToPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToPlaylist'
type MockProvider_AddToPlaylist_Call struct {
	*mock.Call
}

// AddToPlaylist is a helper method to define mock.On call
//   - ctx context.Context
//   - trackID string
func (_e *MockProvider_Expecter) AddToPlaylist(ctx interface{}, trackID interface{}) *MockProvider_AddToPlaylist_Call {
	return &MockProvider_AddToPlaylist_Call{Call: _e.mock.On("AddToPlaylist", ctx, trackID)}
}

func (_c *MockProvider_AddToPlaylist_Call) Run(run func(ctx context.Context, trackID string)) *MockProvider_AddToPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_AddToPlaylist_Call) Return(err error) *MockProvider_AddToPlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_AddToPlaylist_Call) RunAndReturn(run func(ctx context.Context, trackID string) error) *MockProvider_AddToPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function for the type MockProvider
func (_mock *MockProvider) Authenticate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockProvider_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) Authenticate(ctx interface{}) *MockProvider_Authenticate_Call {
	return &MockProvider_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx)}
}

func (_c *MockProvider_Authenticate_Call) Run(run func(ctx context.Context)) *MockProvider_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_Authenticate_Call) Return(err error) *MockProvider_Authenticate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_Authenticate_Call) RunAndReturn(run func(ctx context.Context) error) *MockProvider_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// GetFullPlaylist provides a mock function for the type MockProvider
func (_mock *MockProvider) GetFullPlaylist(ctx context.Context) (*provider.Playlist, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFullPlaylist")
	}

	var r0 *provider.Playlist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*provider.Playlist, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *provider.Playlist); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Playlist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GetFullPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFullPlaylist'
type MockProvider_GetFullPlaylist_Call struct {
	*mock.Call
}

// GetFullPlaylist is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProvider_Expecter) GetFullPlaylist(ctx interface{}) *MockProvider_GetFullPlaylist_Call {
	return &MockProvider_GetFullPlaylist_Call{Call: _e.mock.On("GetFullPlaylist", ctx)}
}

func (_c *MockProvider_GetFullPlaylist_Call) Run(run func(ctx context.Context)) *MockProvider_GetFullPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_GetFullPlaylist_Call) Return(playlist *provider.Playlist, err error) *MockProvider_GetFullPlaylist_Call {
	_c.Call.Return(playlist, err)
	return _c
}

func (_c *MockProvider_GetFullPlaylist_Call) RunAndReturn(run func(ctx context.Context) (*provider.Playlist, error)) *MockProvider_GetFullPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProvider
func (_mock *MockProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(s string) *MockProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockProvider
func (_mock *MockProvider) Search(ctx context.Context, query string) (provider.Track, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 provider.Track
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (provider.Track, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) provider.Track); ok {
		r0 = returnFunc(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(provider.Track)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockProvider_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockProvider_Expecter) Search(ctx interface{}, query interface{}) *MockProvider_Search_Call {
	return &MockProvider_Search_Call{Call: _e.mock.On("Search", ctx, query)}
}

func (_c *MockProvider_Search_Call) Run(run func(ctx context.Context, query string)) *MockProvider_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Search_Call) Return(track provider.Track, err error) *MockProvider_Search_Call {
	_c.Call.Return(track, err)
	return _c
}

func (_c *MockProvider_Search_Call) RunAndReturn(run func(ctx context.Context, query string) (provider.Track, error)) *MockProvider_Search_Call {
	_c.Call.Return(run)
	return _c
}
