// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrack creates a new instance of MockTrack. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrack(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrack {
	mock := &MockTrack{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrack is an autogenerated mock type for the Track type
type MockTrack struct {
	mock.Mock
}

type MockTrack_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrack) EXPECT() *MockTrack_Expecter {
	return &MockTrack_Expecter{mock: &_m.Mock}
}

// GetArtists provides a mock function for the type MockTrack
func (_mock *MockTrack) GetArtists() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetArtists")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockTrack_GetArtists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArtists'
type MockTrack_GetArtists_Call struct {
	*mock.Call
}

// GetArtists is a helper method to define mock.On call
func (_e *MockTrack_Expecter) GetArtists() *MockTrack_GetArtists_Call {
	return &MockTrack_GetArtists_Call{Call: _e.mock.On("GetArtists")}
}

func (_c *MockTrack_GetArtists_Call) Run(run func()) *MockTrack_GetArtists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrack_GetArtists_Call) Return(strings []string) *MockTrack_GetArtists_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockTrack_GetArtists_Call) RunAndReturn(run func() []string) *MockTrack_GetArtists_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockTrack
func (_mock *MockTrack) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTrack_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockTrack_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockTrack_Expecter) GetID() *MockTrack_GetID_Call {
	return &MockTrack_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockTrack_GetID_Call) Run(run func()) *MockTrack_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrack_GetID_Call) Return(s string) *MockTrack_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTrack_GetID_Call) RunAndReturn(run func() string) *MockTrack_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTitle provides a mock function for the type MockTrack
func (_mock *MockTrack) GetTitle() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTitle")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTrack_GetTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTitle'
type MockTrack_GetTitle_Call struct {
	*mock.Call
}

// GetTitle is a helper method to define mock.On call
func (_e *MockTrack_Expecter) GetTitle() *MockTrack_GetTitle_Call {
	return &MockTrack_GetTitle_Call{Call: _e.mock.On("GetTitle")}
}

func (_c *MockTrack_GetTitle_Call) Run(run func()) *MockTrack_GetTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTrack_GetTitle_Call) Return(s string) *MockTrack_GetTitle_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTrack_GetTitle_Call) RunAndReturn(run func() string) *MockTrack_GetTitle_Call {
	_c.Call.Return(run)
	return _c
}
